/laserMapping:
  ros__parameters:
    common:
      #img_topic: "hikrobot_camera/rgb"
      img_topic: "/inference/visualization"
      lid_topic: "/livox/lidar_converted"
      imu_topic: "/livox/imu"
      img_en: 1
      lidar_en: 1
      ros_driver_bug_fix: false

    extrin_calib:
      extrinsic_T: [0.04165, 0.02326, -0.0284]
      extrinsic_R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
      #6.16 calibrate
      Rcl: [-0.999434,  0.033624 ,-0.001414,
        0.001010, -0.012011, -0.999927,
        -0.033639 ,-0.999362,  0.011970] 
      Pcl: [0.137075, 0.027970,-0.054098]

    time_offset: 
      imu_time_offset: 0.0
      img_time_offset: 0.1
      exposure_time_init: 0.0

    preprocess:
      point_filter_num: 1
      filter_size_surf: 0.1
      lidar_type: 1 # Livox Avia LiDAR
      scan_line: 4
      blind: 0.8

    vio:
      max_iterations: 5
      outlier_threshold: 1000.0 # 78 100 156 #100 200 500 700 infinite
      img_point_cov: 100.0 # 100 1000 
      patch_size: 8
      patch_pyrimid_level: 4
      normal_en: true
      raycast_en: false
      inverse_composition_en: false
      exposure_estimate_en: true
      inv_expo_cov: 0.1

    imu:
      imu_en: true
      imu_int_frame: 30
      acc_cov: 0.5 # 0.2
      gyr_cov: 0.3 # 0.5
      b_acc_cov: 0.0001 # 0.1
      b_gyr_cov: 0.0001 # 0.1

    lio:
      max_iterations: 3
      dept_err: 0.02
      beam_err: 0.05
      min_eigen_value: 0.005 # 0.005
      voxel_size: 0.8
      max_layer: 2
      max_points_num: 50
      layer_init_num: [5, 5, 5, 5, 5]

    local_map:  
      map_sliding_en: false
      half_map_size: 100
      sliding_thresh: 8

    uav:
      imu_rate_odom: false
      gravity_align_en: false

    publish:
      dense_map_en: true
      pub_effect_point_en: false 
      pub_plane_en: false
      pub_scan_num: 1
      blind_rgb_points: 0.0

    evo:
      seq_name: "CBD_Building_01"
      pose_output_en: false

    pcd_save:
      pcd_save_en: true
      colmap_output_en: false # need to set interval = -1
      filter_size_pcd: 0.02
      interval: -1
      # how many LiDAR frames saved in each pcd file;
      # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
